### ISSUE TITLE
ImportError: cannot import name '__service_version__'

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/investigator#178]
**Describe the bug**
```
Traceback (most recent call last):
  File "/opt/app-root/bin/faust", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 407, in make_context
    self._maybe_import_app()
  File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 372, in _maybe_import_app
    find_app(appstr)
  File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 299, in find_app
    val = symbol_by_name(app, imp=imp)
  File "/opt/app-root/lib/python3.6/site-packages/mode/utils/imports.py", line 269, in symbol_by_name
    **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/mode/utils/imports.py", line 376, in import_from_cwd
    return imp(module, package=package)
  File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/app-root/src/producer.py", line 23, in <module>
    from thoth.investigator import __service_version__
  File "/opt/app-root/src/thoth/investigator/__init__.py", line 28, in <module>
    from .missing_package import parse_missing_package
  File "/opt/app-root/src/thoth/investigator/missing_package/__init__.py", line 20, in <module>
    from .metrics_missing_package import missing_package_exceptions
  File "/opt/app-root/src/thoth/investigator/missing_package/metrics_missing_package.py", line 20, in <module>
    from thoth.investigator.metrics import in_progress, success, exceptions
  File "/opt/app-root/src/thoth/investigator/metrics.py", line 22, in <module>
    from thoth.investigator import __service_version__
ImportError: cannot import name '__service_version__'
```

**To Reproduce**
Run an adviser job

**Comment by pacospace** [comment]
@KPostOffice you PR solved this?
