### ISSUE TITLE
TypeError: object NoneType can't be used in 'await' expression"

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#264]
**Describe the bug**
TypeError: object NoneType can't be used in 'await' expression"

**To Reproduce**
1. Send message to investigator in version 0.4.10

**Expected behavior**
Schedule SI correctly

**Screenshots**
```
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/faust/agents/agent.py", line 647, in _execute_actor
    await coro
  File "/opt/app-root/src/consumer.py", line 169, in consume_missing_version
    await parse_missing_version(version=missing_version, openshift=openshift, graph=graph)
TypeError: object NoneType can't be used in 'await' expression
[2020-09-25 18:00:16,117] [1] [WARNING] {"name": "faust.agents.actor", "levelname": "ERROR", "module": "logging", "lineno": 267, "funcname": "log", "created": 1601056816.1114268, "asctime": "2020-09-25 18:00:16,111", "msecs": 111.42683029174805, "relative_created": 233699.70774650574, "process": 1, "message": "[^----Agent*: consumer.consume_missing_version]: Crashed reason=TypeError(\"object NoneType can't be used in 'await' expression\",)\nTraceback (most recent call last):\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/agents/agent.py\", line 647, in _execute_actor\n    await coro\n  File \"/opt/app-root/src/consumer.py\", line 169, in consume_missing_version\n    await parse_missing_version(version=missing_version, openshift=openshift, graph=graph)\nTypeError: object NoneType can't be used in 'await' expression"} 
```

**Additional context**

**Comment by pacospace** [comment]
Fixed by https://github.com/thoth-station/investigator/pull/269
