### ISSUE TITLE
Investigator cannot consume package missing

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#283]
**Describe the bug**
Investigator cannot consume package missing

**To Reproduce**
1. Run package update

**Expected behavior**
Investigator can schedule package missing

**Screenshots**
```
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/faust/agents/agent.py", line 647, in _execute_actor
    await coro
  File "/opt/app-root/src/consumer.py", line 162, in consume_missing_package
    await parse_missing_package(package=missing_package, openshift=openshift, graph=graph)
  File "/opt/app-root/src/investigator/investigator/missing_package/investigate_missing_package.py", line 42, in parse_missing_package
    gitservice_repo = git_source_from_url(repo)
  File "/opt/app-root/src/investigator/investigator/common.py", line 250, in git_source_from_url
    service_name = service_url.split(".")[-2]
IndexError: list index out of range
```

**Additional context**

**Comment by KPostOffice** [comment]
I think this is an issue with the url passed. `service_url.split(".")[-2]` should always grab something otherwise we have an ill formed url. `google.com` would get google, the only way the index can be out of range is if it is missing a top level domain.

**Comment by fridex** [comment]
Would something like `urlparse` help here?

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse
