### ISSUE TITLE
New investigator cannot start correctly

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#346]
**Describe the bug**
New investigator cannot start correctly

**To Reproduce**
1. Deploy new investigator using confluent

**Expected behavior**
investigator starts correctly

**Screenshots**
```
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1603437400.6195784, "asctime": "2020-10-23 07:16:40,619", "msecs": 619.5783615112305, "relative_created": 4028.867244720459, "process": 1, "message": "Logging to a Sentry instance is turned off"}
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.advise_justification.investigate_advise_justification' found in sys.modules after import of package 'investigator.investigator.advise_justification', but prior to execution of 'investigator.investigator.advise_justification.investigate_advise_justification'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.adviser_re_run.investigate_adviser_re_run' found in sys.modules after import of package 'investigator.investigator.adviser_re_run', but prior to execution of 'investigator.investigator.adviser_re_run.investigate_adviser_re_run'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.adviser_trigger.investigate_adviser_trigger' found in sys.modules after import of package 'investigator.investigator.adviser_trigger', but prior to execution of 'investigator.investigator.adviser_trigger.investigate_adviser_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.hash_mismatch.investigate_hash_mismatch' found in sys.modules after import of package 'investigator.investigator.hash_mismatch', but prior to execution of 'investigator.investigator.hash_mismatch.investigate_hash_mismatch'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.kebechet_run_url_trigger.investigate_kebechet_run_url_trigger' found in sys.modules after import of package 'investigator.investigator.kebechet_run_url_trigger', but prior to execution of 'investigator.investigator.kebechet_run_url_trigger.investigate_kebechet_run_url_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.kebechet_trigger.investigate_kebechet_trigger' found in sys.modules after import of package 'investigator.investigator.kebechet_trigger', but prior to execution of 'investigator.investigator.kebechet_trigger.investigate_kebechet_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.missing_package.investigate_missing_package' found in sys.modules after import of package 'investigator.investigator.missing_package', but prior to execution of 'investigator.investigator.missing_package.investigate_missing_package'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.missing_version.investigate_missing_version' found in sys.modules after import of package 'investigator.investigator.missing_version', but prior to execution of 'investigator.investigator.missing_version.investigate_missing_version'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.package_extract_trigger.investigate_package_extract_trigger' found in sys.modules after import of package 'investigator.investigator.package_extract_trigger', but prior to execution of 'investigator.investigator.package_extract_trigger.investigate_package_extract_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.package_released.investigate_package_released' found in sys.modules after import of package 'investigator.investigator.package_released', but prior to execution of 'investigator.investigator.package_released.investigate_package_released'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.provenance_checker_trigger.investigate_provenance_checker_trigger' found in sys.modules after import of package 'investigator.investigator.provenance_checker_trigger', but prior to execution of 'investigator.investigator.provenance_checker_trigger.investigate_provenance_checker_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.qebhwt_trigger.investigate_qebhwt_trigger' found in sys.modules after import of package 'investigator.investigator.qebhwt_trigger', but prior to execution of 'investigator.investigator.qebhwt_trigger.investigate_qebhwt_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.si_unanalyzed_package.investigate_si_unanalyzed_package' found in sys.modules after import of package 'investigator.investigator.si_unanalyzed_package', but prior to execution of 'investigator.investigator.si_unanalyzed_package.investigate_si_unanalyzed_package'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.solved_package.investigate_solved_package' found in sys.modules after import of package 'investigator.investigator.solved_package', but prior to execution of 'investigator.investigator.solved_package.investigate_solved_package'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.unresolved_package.investigate_unresolved_package' found in sys.modules after import of package 'investigator.investigator.unresolved_package', but prior to execution of 'investigator.investigator.unresolved_package.investigate_unresolved_package'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.unrevsolved_package.investigate_unrevsolved_package' found in sys.modules after import of package 'investigator.investigator.unrevsolved_package', but prior to execution of 'investigator.investigator.unrevsolved_package.investigate_unrevsolved_package'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.update_provide_source_distro.investigate_update_provide_source_distro' found in sys.modules after import of package 'investigator.investigator.update_provide_source_distro', but prior to execution of 'investigator.investigator.update_provide_source_distro.investigate_update_provide_source_distro'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1603437401.421184, "asctime": "2020-10-23 07:16:41,421", "msecs": 421.1840629577637, "relative_created": 4830.472946166992, "process": 1, "message": "Logging to a Sentry instance is turned off"}
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1603437401.421184, "asctime": "2020-10-23 07:16:41,421", "msecs": 421.1840629577637, "relative_created": 4830.472946166992, "process": 1, "message": "Logging to a Sentry instance is turned off"}
{"name": "thoth.common.openshift", "levelname": "WARNING", "module": "openshift", "lineno": 158, "funcname": "__init__", "created": 1603437401.4893942, "asctime": "2020-10-23 07:16:41,489", "msecs": 489.3941879272461, "relative_created": 4898.683071136475, "process": 1, "message": "TLS verification when communicating with k8s/okd master is disabled"}
{"name": "thoth.common.openshift", "levelname": "WARNING", "module": "openshift", "lineno": 158, "funcname": "__init__", "created": 1603437401.4893942, "asctime": "2020-10-23 07:16:41,489", "msecs": 489.3941879272461, "relative_created": 4898.683071136475, "process": 1, "message": "TLS verification when communicating with k8s/okd master is disabled"}
Traceback (most recent call last):
  File "consumer.py", line 163, in <module>
    c = consumer.create_consumer()
  File "/opt/app-root/lib/python3.6/site-packages/thoth/messaging/consumer.py", line 34, in create_consumer
    return Consumer(kafka_config_from_env())
ValueError: Failed to create consumer: group.id must be set
```

**Additional context**

**Comment by KPostOffice** [comment]
I will update `thoth-application` templates
