### ISSUE TITLE
Failed to create consumer

### ISSUE THREAD

**Issue by harshad16** [thoth-station/investigator#435]
**Describe the bug**

investigator v0.8.2 is causing this issue in the **stage** cluster.

```
Traceback (most recent call last):
  File "consumer.py", line 165, in <module>
    c = consumer.create_consumer()
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/messaging/consumer.py", line 34, in create_consumer
    return Consumer(kafka_config_from_env())
ValueError: Failed to create consumer: group.id must be set
```

**To Reproduce**
1. Go to logs of the investigator
2. See an error

**Expected behavior**

investigator runs successfully.

**Comment by harshad16** [comment]
This issue happened due to an un-updated deployment config. 
with the updated deploymentconfig, the investigator runs successfully.
