### ISSUE TITLE
Fails in consuming the graph-refresh unresolved message

### ISSUE THREAD

**Issue by harshad16** [thoth-station/investigator#439]
**Describe the bug**
```
Traceback (most recent call last):
  File "consumer.py", line 263, in <module>
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "consumer.py", line 225, in _confluent_consumer_loop
    func = _handler_lookup(msg.topic(), v)
  File "consumer.py", line 111, in _handler_lookup
    return handler_table[topic_name][version]
KeyError: None
```

**To Reproduce**
1. Run graph-refresh job

**Comment by harshad16** [comment]
This was fixed with the version update and fixing the default version.
No more causes issue.
closing.
